$: << '.'

module Kaiseki
	autoload :AndPredicate,			'grammar/and_predicate'
	autoload :ArrayResult,			'grammar/array_result'
	autoload :EOFParslet,			'grammar/eof_parslet'
	autoload :NotPredicate,			'grammar/not_predicate'
	autoload :ParseError,			'grammar/parse_error'
	autoload :Parslet,				'grammar/parslet'
	autoload :ParsletChoice,		'grammar/parslet_choice'
	autoload :ParsletCombination,	'grammar/parslet_combination'
	autoload :ParsletMerger,		'grammar/parslet_merger'
	autoload :ParsletOmission,		'grammar/parslet_omission'
	autoload :ParsletRepetition,	'grammar/parslet_repetition'
	autoload :ParsletSequence,		'grammar/parslet_sequence'
	autoload :Predicate,			'grammar/predicate.rb'
	autoload :ProcParslet,			'grammar/proc_parslet'
	autoload :RegexpParslet,		'grammar/regexp_parslet'
	autoload :Stream,				'grammar/stream'
	autoload :StringParslet,		'grammar/string_parslet'
	autoload :StringResult,			'grammar/string_result'
end